<?php
$sku = $block->GetCurrentSku()->getSku();
//var_dump($bb->getSku());
$end = $block->GetDeal($sku, 'time_end');
//var_dump($end);
//exit;
//$product = $block->GetProduct();
//
//$bb = [];
//foreach ($product as $item) {
//    $bb[] = $item->getData();
//}
//var_dump($bb);
//exit;
//var_dump($product);
//die($product);
//$bb = [];
//foreach ($product as $item){
//    $bb[] = $item->getData('time_start');
//}
//$id = 7;
//$c = $block->get($id);
//$start = $c->getData('time_start');
//$end = $c->getData('time_end');
//var_dump($c->getData('time_start'));
//var_dump($c->getData('time_end'));
//exit;
?>
<!--<button>--><?php //echo $c->getData('time_start') ?><!--</button>-->
<!--<button id="blah">Blah</button>-->
<div class="countdown">
    <div id="day">NA</div>
    <div id="hour">NA</div>
    <div id="minute">NA</div>
    <div id="second">NA</div>
</div>
<script>
     // var countDate = new Date('2021-01-01 00:00:00').getTime();
     var end = new Date('<?php echo $end ?>').getTime();
     function countdown(){
         //var start = new Date('<?php //echo $start ?>//').getTime();
         var now = new Date().getTime();
         // gap = countDate - now;
         gap = end - now;
         var second = 1000;
         var minute = second * 60;
         var hour = minute * 60;
         var day = hour * 24;
         var d = Math.floor(gap / (day));
         var h = Math.floor((gap % (day)) / (hour));
         var m = Math.floor((gap % (hour)) / (minute));
         var w = Math.floor((gap % (minute)) / second);

         document.getElementById('day').innerHTML = d;
         document.getElementById('hour').innerHTML = h;
         document.getElementById('minute').innerHTML = m;
         document.getElementById('second').innerHTML = w;
         if (gap < 0){
             document.getElementById("day").innerHTML = "-1";
             document.getElementById("hour").innerHTML = "-1";
             document.getElementById("minute").innerHTML = "-1";
             document.getElementById("second").innerHTML = "-1";
         }
     }
     setInterval(function (){
         countdown();
     },1000)
    //var start = "<?php //echo $start ?>//";
    //var end = "<?php //echo $end ?>//";
    //function Blah(){
    //   document.getElementById("timeout").innerHTML = start;
    //   document.getElementById("blah").innerHTML = end;
    //}
    //Blah();
    // var so = 10;
    // function Timeout(){
    //     so--;
    //     if (so !== 0) {
    //         document.getElementById("timeout").innerHTML = so;
    //         setTimeout("Timeout()",1000);
    //     } else {
    //         document.getElementById("timeout").innerHTML = "End Game";
    //     }
    // }
    // Timeout();
</script>
