<?php
$sku = $block->GetCurrentSku()->getSku();
$end = $block->GetDeal($sku, 'time_end');
$start = $block->GetDeal($sku, 'time_start');
?>
<div class="countdown">
    <h1 id="time"></h1>
</div>
<script>
    var end = new Date('<?php echo $end ?>').getTime();
    var start = new Date('<?php echo $start ?>').getTime();

    function countdown() {
        if (!isNaN(end)){
            var now = new Date().getTime();
            gap = end - now;
            gao = now - start;
            var second = 1000;
            var minute = second * 60;
            var hour = minute * 60;
            var day = hour * 24;
            var d = Math.floor(gap / (day));
            var h = Math.floor((gap % (day)) / (hour));
            var m = Math.floor((gap % (hour)) / (minute));
            var w = Math.floor((gap % (minute)) / second);
            var time = d + " Days-" + h + " Hours-" + m + " Minutes-" + w + " Seconds";

            document.getElementById("time").innerHTML = time;
            if (gap < 0) {
                document.getElementById("time").innerHTML = "End Deal!";
            }else if (gao < 0){
                document.getElementById("time").innerHTML = "Deal will be start in <?php echo $start ?>";
            }
        }
    }
    setInterval(function () {
        countdown();
    }, 1000)
</script>
